[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
tic_tac_toc = "3kK4ni8Z9TdjTz87HWcpG8ps9Ps29GpWAz7mJtWEKQfa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/apple/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
